name: ${project.artifactId}
author: PseudoResonance
main: io.github.pseudoresonance.pseudoenchants.PseudoEnchants
version: ${revision}
description: Adds custom enchantments
api-version: 1.13
depend: [PseudoAPI]
softdepend: [WorldGuard]
commands:
  pseudoenchants:
    description: PseudoEnchants Menu
permissions:
  pseudoenchants.reload:
    description: Allows the player to reload the plugin
    default: op
  pseudoenchants.reset:
    description: Allows the player to reset the config
    default: op
    children:
      pseudoenchants.reload: true
  pseudoenchants.reloadlocalization:
    description: Allows the player to reload the localization
    default: op
  pseudoenchants.resetlocalization:
    description: Allows the player to reset the localization
    default: op
    children:
      pseudoenchants.reloadlocalization: true
  pseudoenchants.*:
    description: Gives the user all PseudoEnchants permissions
    default: op
    children:
      pseudoenchants.reset: true
      pseudoenchants.resetlocalization: true